// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A single Android device.
public struct AndroidDevice: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The id of the Android device to be used.
  /// Use the TestEnvironmentDiscoveryService to get supported options.
  public var androidModelId: Swift.String = Swift.String()

  /// Required. The id of the Android OS version to be used.
  /// Use the TestEnvironmentDiscoveryService to get supported options.
  public var androidVersionId: Swift.String = Swift.String()

  /// Optional. The locale the test device used for testing.
  /// Use the TestEnvironmentDiscoveryService to get supported options.
  public var locale: Swift.String = Swift.String()

  /// Optional. How the device is oriented during the test.
  /// Use the TestEnvironmentDiscoveryService to get supported options.
  public var orientation: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `AndroidDevice`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AndroidDevice().with { $0.androidModelId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let androidModelId = CodingKeys(stringValue: "androidModelId")
    static let androidVersionId = CodingKeys(stringValue: "androidVersionId")
    static let locale = CodingKeys(stringValue: "locale")
    static let orientation = CodingKeys(stringValue: "orientation")

    static let _knownKeys: Set<Swift.String> = [
      "androidModelId",
      "androidVersionId",
      "locale",
      "orientation",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .androidModelId) {
      self.androidModelId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .androidVersionId) {
      self.androidVersionId = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locale) {
      self.locale = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orientation) {
      self.orientation = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.androidModelId, forKey: .androidModelId)
    try container.encode(self.androidVersionId, forKey: .androidVersionId)
    try container.encode(self.locale, forKey: .locale)
    try container.encode(self.orientation, forKey: .orientation)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.devicestreaming.v1.AndroidDevice"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
