// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A single Android device.
public struct AndroidDevice: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The id of the Android device to be used.
  /// Use the TestEnvironmentDiscoveryService to get supported options.
  public var androidModelId: Swift.String = Swift.String()

  /// Required. The id of the Android OS version to be used.
  /// Use the TestEnvironmentDiscoveryService to get supported options.
  public var androidVersionId: Swift.String = Swift.String()

  /// Optional. The locale the test device used for testing.
  /// Use the TestEnvironmentDiscoveryService to get supported options.
  public var locale: Swift.String = Swift.String()

  /// Optional. How the device is oriented during the test.
  /// Use the TestEnvironmentDiscoveryService to get supported options.
  public var orientation: Swift.String = Swift.String()

  /// Initialize a new instance of `AndroidDevice`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AndroidDevice().with { $0.androidModelId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.devicestreaming.v1.AndroidDevice"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
