// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A message returned from a device.
public struct DeviceMessage: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var contents: OneOf_Contents? = nil

  /// Initialize a new instance of `DeviceMessage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeviceMessage().with { $0.statusUpdate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case statusUpdate = "statusUpdate"
    case streamStatus = "streamStatus"
    case streamData = "streamData"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var contents: OneOf_Contents? = nil
    let contentsCheckAndSet = {
      if contents != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'contents'"))
      }
      contents = $0
    }
    if let statusUpdate = try container.decodeIfPresent(StatusUpdate?.self, forKey: .statusUpdate) {
      try contentsCheckAndSet(.statusUpdate(statusUpdate))
    }
    if let streamStatus = try container.decodeIfPresent(StreamStatus?.self, forKey: .streamStatus) {
      try contentsCheckAndSet(.streamStatus(streamStatus))
    }
    if let streamData = try container.decodeIfPresent(StreamData?.self, forKey: .streamData) {
      try contentsCheckAndSet(.streamData(streamData))
    }
    self.contents = contents
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.contents {
      switch choice {
      case .statusUpdate(let value):
        try container.encode(value, forKey: .statusUpdate)
      case .streamStatus(let value):
        try container.encode(value, forKey: .streamStatus)
      case .streamData(let value):
        try container.encode(value, forKey: .streamData)
      }
    }
  }

  public enum OneOf_Contents: Codable, Equatable, Sendable {
    /// Information about the device's state.
    indirect case statusUpdate(StatusUpdate?)
    /// The result of a device stream from ADB.
    indirect case streamStatus(StreamStatus?)
    /// Data from an open stream.
    indirect case streamData(StreamData?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.devicestreaming.v1.DeviceMessage"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
