// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Protobuf message describing the device message, used from several RPCs.
public struct DeviceSession: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. Name of the DeviceSession, e.g.
  /// "projects/{project_id}/deviceSessions/{session_id}"
  public var name: Swift.String = Swift.String()

  /// Output only. The title of the DeviceSession to be presented in the UI.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Current state of the DeviceSession.
  public var state: DeviceSession.SessionState = DeviceSession.SessionState()

  /// Output only. The historical state transitions of the session_state message
  /// including the current session state.
  public var stateHistories: [DeviceSession.SessionStateEvent] = []

  /// Output only. The interval of time that this device must be interacted with
  /// before it transitions from ACTIVE to TIMEOUT_INACTIVITY.
  public var inactivityTimeout: GoogleCloudWkt.Duration? = nil

  /// Output only. The time that the Session was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The timestamp that the session first became ACTIVE.
  public var activeStartTime: GoogleCloudWkt.Timestamp? = nil

  /// Required. The requested device
  public var androidDevice: AndroidDevice? = nil

  /// The amount of time that a device will be initially allocated for.
  public var expiration: OneOf_Expiration? = nil

  /// Initialize a new instance of `DeviceSession`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeviceSession().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case displayName = "displayName"
    case state = "state"
    case stateHistories = "stateHistories"
    case ttl = "ttl"
    case expireTime = "expireTime"
    case inactivityTimeout = "inactivityTimeout"
    case createTime = "createTime"
    case activeStartTime = "activeStartTime"
    case androidDevice = "androidDevice"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
    self.state = try container.decode(DeviceSession.SessionState.self, forKey: .state)
    self.stateHistories = try container.decode(
      [DeviceSession.SessionStateEvent].self, forKey: .stateHistories)
    self.inactivityTimeout = try container.decodeIfPresent(
      GoogleCloudWkt.Duration.self, forKey: .inactivityTimeout)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.activeStartTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .activeStartTime)
    self.androidDevice = try container.decodeIfPresent(AndroidDevice.self, forKey: .androidDevice)

    var expiration: OneOf_Expiration? = nil
    let expirationCheckAndSet = {
      if expiration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'expiration'"))
      }
      expiration = $0
    }
    if let ttl = try container.decodeIfPresent(GoogleCloudWkt.Duration?.self, forKey: .ttl) {
      try expirationCheckAndSet(.ttl(ttl))
    }
    if let expireTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp?.self, forKey: .expireTime)
    {
      try expirationCheckAndSet(.expireTime(expireTime))
    }
    self.expiration = expiration
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateHistories, forKey: .stateHistories)
    try container.encode(self.inactivityTimeout, forKey: .inactivityTimeout)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.activeStartTime, forKey: .activeStartTime)
    try container.encode(self.androidDevice, forKey: .androidDevice)

    if let choice = self.expiration {
      switch choice {
      case .ttl(let value):
        try container.encode(value, forKey: .ttl)
      case .expireTime(let value):
        try container.encode(value, forKey: .expireTime)
      }
    }
  }

  /// A message encapsulating a series of Session states and the time that the
  /// DeviceSession first entered those states.
  public struct SessionStateEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The session_state tracked by this event
    public var sessionState: DeviceSession.SessionState = DeviceSession.SessionState()

    /// Output only. The time that the session_state first encountered that
    /// state.
    public var eventTime: GoogleCloudWkt.Timestamp? = nil

    /// Output only. A human-readable message to explain the state.
    public var stateMessage: Swift.String = Swift.String()

    /// Initialize a new instance of `SessionStateEvent`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SessionStateEvent().with { $0.sessionState = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.devicestreaming.v1.DeviceSession.SessionStateEvent"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The state that the DeviceSession resides.
  public enum SessionState: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Initial state of a session request. The session is being validated for
    /// correctness and a device is not yet requested.
    case requested
    /// The session has been validated and is in the queue for a device.
    case pending
    /// The session has been granted and the device is accepting
    /// connections.
    case active
    /// The session duration exceeded the device's reservation time period and
    /// timed out automatically.
    case expired
    /// The user is finished with the session and it was canceled by the user
    /// while the request was still getting allocated or after allocation and
    /// during device usage period.
    case finished
    /// Unable to complete the session because the device was unavailable and
    /// it failed to allocate through the scheduler. For example, a device not
    /// in the catalog was requested or the request expired in the allocation
    /// queue.
    case unavailable
    /// Unable to complete the session for an internal reason, such as an
    /// infrastructure failure.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .requested: return 1
      case .pending: return 2
      case .active: return 3
      case .expired: return 4
      case .finished: return 5
      case .unavailable: return 6
      case .error: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SESSION_STATE_UNSPECIFIED"
      case .requested: return "REQUESTED"
      case .pending: return "PENDING"
      case .active: return "ACTIVE"
      case .expired: return "EXPIRED"
      case .finished: return "FINISHED"
      case .unavailable: return "UNAVAILABLE"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SessionState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SESSION_STATE_UNSPECIFIED": self = .unspecified
      case "REQUESTED": self = .requested
      case "PENDING": self = .pending
      case "ACTIVE": self = .active
      case "EXPIRED": self = .expired
      case "FINISHED": self = .finished
      case "UNAVAILABLE": self = .unavailable
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SessionState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .requested
      case 2: self = .pending
      case 3: self = .active
      case 4: self = .expired
      case 5: self = .finished
      case 6: self = .unavailable
      case 7: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .requested: return try container.encode(1)
      case .pending: return try container.encode(2)
      case .active: return try container.encode(3)
      case .expired: return try container.encode(4)
      case .finished: return try container.encode(5)
      case .unavailable: return try container.encode(6)
      case .error: return try container.encode(7)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The amount of time that a device will be initially allocated for.
  public enum OneOf_Expiration: Codable, Equatable, Sendable {
    /// Optional. The amount of time that a device will be initially allocated
    /// for. This can eventually be extended with the UpdateDeviceSession RPC.
    /// Default: 15 minutes.
    indirect case ttl(GoogleCloudWkt.Duration?)
    /// Optional. If the device is still in use at this time, any connections
    /// will be ended and the SessionState will transition from ACTIVE to
    /// FINISHED.
    indirect case expireTime(GoogleCloudWkt.Timestamp?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.devicestreaming.v1.DeviceSession"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
