// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Protobuf message describing the device message, used from several RPCs.
public struct DeviceSession: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Name of the DeviceSession, e.g.
  /// "projects/{project_id}/deviceSessions/{session_id}"
  public var name: Swift.String = Swift.String()

  /// Output only. The title of the DeviceSession to be presented in the UI.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Current state of the DeviceSession.
  public var state: DeviceSession.SessionState = DeviceSession.SessionState()

  /// Output only. The historical state transitions of the session_state message
  /// including the current session state.
  public var stateHistories: [DeviceSession.SessionStateEvent] = []

  /// Output only. The interval of time that this device must be interacted with
  /// before it transitions from ACTIVE to TIMEOUT_INACTIVITY.
  public var inactivityTimeout: GoogleWKT.Duration? = nil

  /// Output only. The time that the Session was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The timestamp that the session first became ACTIVE.
  public var activeStartTime: GoogleWKT.Timestamp? = nil

  /// Required. The requested device
  public var androidDevice: AndroidDevice? = nil

  /// The amount of time that a device will be initially allocated for.
  public var expiration: OneOf_Expiration? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DeviceSession`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeviceSession().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let state = CodingKeys(stringValue: "state")
    static let stateHistories = CodingKeys(stringValue: "stateHistories")
    static let ttl = CodingKeys(stringValue: "ttl")
    static let expireTime = CodingKeys(stringValue: "expireTime")
    static let inactivityTimeout = CodingKeys(stringValue: "inactivityTimeout")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let activeStartTime = CodingKeys(stringValue: "activeStartTime")
    static let androidDevice = CodingKeys(stringValue: "androidDevice")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "state",
      "stateHistories",
      "ttl",
      "expireTime",
      "inactivityTimeout",
      "createTime",
      "activeStartTime",
      "androidDevice",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(DeviceSession.SessionState.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(
      [DeviceSession.SessionStateEvent].self, forKey: .stateHistories)
    {
      self.stateHistories = value
    }
    self.inactivityTimeout = try container.decodeIfPresent(
      GoogleWKT.Duration.self, forKey: .inactivityTimeout)
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.activeStartTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .activeStartTime)
    self.androidDevice = try container.decodeIfPresent(AndroidDevice.self, forKey: .androidDevice)

    var expiration: OneOf_Expiration? = nil
    let expirationCheckAndSet = {
      if expiration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'expiration'"))
      }
      expiration = $0
    }
    if let ttl = try container.decodeIfPresent(GoogleWKT.Duration?.self, forKey: .ttl) {
      try expirationCheckAndSet(.ttl(ttl))
    }
    if let expireTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp?.self, forKey: .expireTime)
    {
      try expirationCheckAndSet(.expireTime(expireTime))
    }
    self.expiration = expiration
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.stateHistories, forKey: .stateHistories)
    try container.encodeIfPresent(self.inactivityTimeout, forKey: .inactivityTimeout)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.activeStartTime, forKey: .activeStartTime)
    try container.encodeIfPresent(self.androidDevice, forKey: .androidDevice)

    if let choice = self.expiration {
      switch choice {
      case .ttl(let value):
        try container.encode(value, forKey: .ttl)
      case .expireTime(let value):
        try container.encode(value, forKey: .expireTime)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A message encapsulating a series of Session states and the time that the
  /// DeviceSession first entered those states.
  public struct SessionStateEvent: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The session_state tracked by this event
    public var sessionState: DeviceSession.SessionState = DeviceSession.SessionState()

    /// Output only. The time that the session_state first encountered that
    /// state.
    public var eventTime: GoogleWKT.Timestamp? = nil

    /// Output only. A human-readable message to explain the state.
    public var stateMessage: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SessionStateEvent`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SessionStateEvent().with { $0.sessionState = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sessionState = CodingKeys(stringValue: "sessionState")
      static let eventTime = CodingKeys(stringValue: "eventTime")
      static let stateMessage = CodingKeys(stringValue: "stateMessage")

      static let _knownKeys: Set<Swift.String> = [
        "sessionState",
        "eventTime",
        "stateMessage",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        DeviceSession.SessionState.self, forKey: .sessionState)
      {
        self.sessionState = value
      }
      self.eventTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .eventTime)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .stateMessage) {
        self.stateMessage = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sessionState, forKey: .sessionState)
      try container.encodeIfPresent(self.eventTime, forKey: .eventTime)
      try container.encode(self.stateMessage, forKey: .stateMessage)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.devicestreaming.v1.DeviceSession.SessionStateEvent"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The state that the DeviceSession resides.
  public enum SessionState: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Initial state of a session request. The session is being validated for
    /// correctness and a device is not yet requested.
    case requested
    /// The session has been validated and is in the queue for a device.
    case pending
    /// The session has been granted and the device is accepting
    /// connections.
    case active
    /// The session duration exceeded the device's reservation time period and
    /// timed out automatically.
    case expired
    /// The user is finished with the session and it was canceled by the user
    /// while the request was still getting allocated or after allocation and
    /// during device usage period.
    case finished
    /// Unable to complete the session because the device was unavailable and
    /// it failed to allocate through the scheduler. For example, a device not
    /// in the catalog was requested or the request expired in the allocation
    /// queue.
    case unavailable
    /// Unable to complete the session for an internal reason, such as an
    /// infrastructure failure.
    case error
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .requested: return 1
      case .pending: return 2
      case .active: return 3
      case .expired: return 4
      case .finished: return 5
      case .unavailable: return 6
      case .error: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SESSION_STATE_UNSPECIFIED"
      case .requested: return "REQUESTED"
      case .pending: return "PENDING"
      case .active: return "ACTIVE"
      case .expired: return "EXPIRED"
      case .finished: return "FINISHED"
      case .unavailable: return "UNAVAILABLE"
      case .error: return "ERROR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SessionState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SESSION_STATE_UNSPECIFIED": self = .unspecified
      case "REQUESTED": self = .requested
      case "PENDING": self = .pending
      case "ACTIVE": self = .active
      case "EXPIRED": self = .expired
      case "FINISHED": self = .finished
      case "UNAVAILABLE": self = .unavailable
      case "ERROR": self = .error
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SessionState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .requested
      case 2: self = .pending
      case 3: self = .active
      case 4: self = .expired
      case 5: self = .finished
      case 6: self = .unavailable
      case 7: self = .error
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("SESSION_STATE_UNSPECIFIED")
      case .requested: return try container.encode("REQUESTED")
      case .pending: return try container.encode("PENDING")
      case .active: return try container.encode("ACTIVE")
      case .expired: return try container.encode("EXPIRED")
      case .finished: return try container.encode("FINISHED")
      case .unavailable: return try container.encode("UNAVAILABLE")
      case .error: return try container.encode("ERROR")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The amount of time that a device will be initially allocated for.
  public enum OneOf_Expiration: Codable, Equatable, Sendable {
    /// Optional. The amount of time that a device will be initially allocated
    /// for. This can eventually be extended with the UpdateDeviceSession RPC.
    /// Default: 15 minutes.
    indirect case ttl(GoogleWKT.Duration?)
    /// Optional. If the device is still in use at this time, any connections
    /// will be ended and the SessionState will transition from ACTIVE to
    /// FINISHED.
    indirect case expireTime(GoogleWKT.Timestamp?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.devicestreaming.v1.DeviceSession"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
