// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// A service for allocating Android devices and interacting with the
/// live-allocated devices.
///
/// Each Session will wait for available capacity, at a higher
/// priority over Test Execution. When allocated, the session will be exposed
/// through a stream for integration.
///
/// DirectAccessService is currently available as a preview to select developers.
/// You can register today on behalf of you and your team at
/// https://developer.android.com/studio/preview/android-device-streaming
///
/// @Snippet(path: "DirectAccessServiceQuickstart")
public final class DirectAccessServiceClient: Clients.DirectAccessServiceProtocol, Sendable {
  let inner: any Clients.DirectAccessServiceStub

  /// Creates a new `DirectAccessServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.DirectAccessServiceStub = try Clients.DirectAccessServiceTransport(
      options)
    inner = Clients.DirectAccessServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DirectAccessServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a DeviceSession.
  ///
  /// @Snippet(path: "DirectAccessService_CreateDeviceSession")
  public func createDeviceSession(
    request: CreateDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    try await self.inner.createDeviceSession(request: request, options: options)
  }

  /// Lists DeviceSessions owned by the project user.
  ///
  /// @Snippet(path: "DirectAccessService_ListDeviceSessions")
  public func listDeviceSessions(
    request: ListDeviceSessionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeviceStreamingV1.ListDeviceSessionsResponse {
    try await self.inner.listDeviceSessions(request: request, options: options)
  }

  /// Lists DeviceSessions owned by the project user.
  ///
  /// @Snippet(path: "DirectAccessService_ListDeviceSessions")
  public func listDeviceSessions(
    byItem: ListDeviceSessionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DeviceSession, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDeviceStreamingV1.ListDeviceSessionsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listDeviceSessions(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a DeviceSession, which documents the allocation status and
  /// whether the device is allocated. Clients making requests from this API
  /// must poll GetDeviceSession.
  ///
  /// @Snippet(path: "DirectAccessService_GetDeviceSession")
  public func getDeviceSession(
    request: GetDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    try await self.inner.getDeviceSession(request: request, options: options)
  }

  /// Cancel a DeviceSession.
  /// This RPC changes the DeviceSession to state FINISHED and terminates all
  /// connections.
  /// Canceled sessions are not deleted and can be retrieved or
  /// listed by the user until they expire based on the 28 day deletion policy.
  ///
  /// @Snippet(path: "DirectAccessService_CancelDeviceSession")
  public func cancelDeviceSession(
    request: CancelDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelDeviceSession(request: request, options: options)
  }

  /// Updates the current DeviceSession to the fields described by the
  /// update_mask.
  ///
  /// @Snippet(path: "DirectAccessService_UpdateDeviceSession")
  public func updateDeviceSession(
    request: UpdateDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    try await self.inner.updateDeviceSession(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DirectAccessServiceClient`.
  ///
  /// To mock `DirectAccessServiceClient` change your functions to receive
  /// `some DirectAccessServiceProtocol` or `any DirectAccessServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DirectAccessServiceProtocol {
    /// See `DirectAccessServiceClient.createDeviceSession`.
    func createDeviceSession(request: CreateDeviceSessionRequest) async throws
      -> GoogleCloudDeviceStreamingV1.DeviceSession

    /// See `DirectAccessServiceClient.createDeviceSession`.
    func createDeviceSession(
      parent: Swift.String,
      deviceSession: DeviceSession?,
      deviceSessionId: Swift.String,
    ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession

    /// See `DirectAccessServiceClient.listDeviceSessions`.
    func listDeviceSessions(request: ListDeviceSessionsRequest) async throws
      -> GoogleCloudDeviceStreamingV1.ListDeviceSessionsResponse

    /// See `DirectAccessServiceClient.listDeviceSessions`.
    func listDeviceSessions(
      byItem: ListDeviceSessionsRequest
    ) throws -> any AsyncSequence<DeviceSession, Swift.Error>

    /// See `DirectAccessServiceClient.listDeviceSessions`.
    func listDeviceSessions(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DeviceSession, Swift.Error>

    /// See `DirectAccessServiceClient.getDeviceSession`.
    func getDeviceSession(request: GetDeviceSessionRequest) async throws
      -> GoogleCloudDeviceStreamingV1.DeviceSession

    /// See `DirectAccessServiceClient.getDeviceSession`.
    func getDeviceSession(
      name: Swift.String,
    ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession

    /// See `DirectAccessServiceClient.cancelDeviceSession`.
    func cancelDeviceSession(request: CancelDeviceSessionRequest) async throws

    /// See `DirectAccessServiceClient.updateDeviceSession`.
    func updateDeviceSession(request: UpdateDeviceSessionRequest) async throws
      -> GoogleCloudDeviceStreamingV1.DeviceSession

    /// See `DirectAccessServiceClient.updateDeviceSession`.
    func updateDeviceSession(
      deviceSession: DeviceSession?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession

    /// See `DirectAccessServiceClient.createDeviceSession`.
    func createDeviceSession(
      request: CreateDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession

    /// See `DirectAccessServiceClient.listDeviceSessions`.
    func listDeviceSessions(
      request: ListDeviceSessionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeviceStreamingV1.ListDeviceSessionsResponse

    /// See `DirectAccessServiceClient.listDeviceSessions`.
    func listDeviceSessions(
      byItem: ListDeviceSessionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<DeviceSession, Swift.Error>

    /// See `DirectAccessServiceClient.getDeviceSession`.
    func getDeviceSession(
      request: GetDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession

    /// See `DirectAccessServiceClient.cancelDeviceSession`.
    func cancelDeviceSession(
      request: CancelDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DirectAccessServiceClient.updateDeviceSession`.
    func updateDeviceSession(
      request: UpdateDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession
  }
}

// Default implementations
extension Clients.DirectAccessServiceProtocol {
  public func createDeviceSession(request: CreateDeviceSessionRequest) async throws
    -> GoogleCloudDeviceStreamingV1.DeviceSession
  {
    try await self.createDeviceSession(request: request, options: .init())
  }

  public func createDeviceSession(
    request: CreateDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createDeviceSession(
    parent: Swift.String,
    deviceSession: DeviceSession?,
    deviceSessionId: Swift.String,
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    let request = CreateDeviceSessionRequest().with {
      $0.parent = parent
      $0.deviceSession = deviceSession
      $0.deviceSessionId = deviceSessionId
    }
    return try await self.createDeviceSession(request: request)
  }

  public func listDeviceSessions(request: ListDeviceSessionsRequest) async throws
    -> GoogleCloudDeviceStreamingV1.ListDeviceSessionsResponse
  {
    try await self.listDeviceSessions(request: request, options: .init())
  }

  public func listDeviceSessions(
    request: ListDeviceSessionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeviceStreamingV1.ListDeviceSessionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDeviceSessions(
    byItem: ListDeviceSessionsRequest
  ) throws -> any AsyncSequence<DeviceSession, Swift.Error> {
    try self.listDeviceSessions(byItem: byItem, options: .init())
  }

  public func listDeviceSessions(
    byItem: ListDeviceSessionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<DeviceSession, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDeviceStreamingV1.ListDeviceSessionsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDeviceSessions(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DeviceSession, Swift.Error> {
    let request = ListDeviceSessionsRequest().with {
      $0.parent = parent
    }
    return try self.listDeviceSessions(byItem: request)
  }

  public func getDeviceSession(request: GetDeviceSessionRequest) async throws
    -> GoogleCloudDeviceStreamingV1.DeviceSession
  {
    try await self.getDeviceSession(request: request, options: .init())
  }

  public func getDeviceSession(
    request: GetDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDeviceSession(
    name: Swift.String,
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    let request = GetDeviceSessionRequest().with {
      $0.name = name
    }
    return try await self.getDeviceSession(request: request)
  }

  public func cancelDeviceSession(request: CancelDeviceSessionRequest) async throws {
    try await self.cancelDeviceSession(request: request, options: .init())
  }

  public func cancelDeviceSession(
    request: CancelDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateDeviceSession(request: UpdateDeviceSessionRequest) async throws
    -> GoogleCloudDeviceStreamingV1.DeviceSession
  {
    try await self.updateDeviceSession(request: request, options: .init())
  }

  public func updateDeviceSession(
    request: UpdateDeviceSessionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateDeviceSession(
    deviceSession: DeviceSession?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudDeviceStreamingV1.DeviceSession {
    let request = UpdateDeviceSessionRequest().with {
      $0.deviceSession = deviceSession
      $0.updateMask = updateMask
    }
    return try await self.updateDeviceSession(request: request)
  }
}
