// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A StatusUpdate message given over the ADB protocol for the device state.
public struct StatusUpdate: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The device's state
  public var state: StatusUpdate.DeviceState = StatusUpdate.DeviceState()

  /// A map of properties with information about this device.
  public var properties: [Swift.String: Swift.String] = [:]

  /// A comma-separated list of "features" that this device supports.
  public var features: Swift.String = Swift.String()

  /// Initialize a new instance of `StatusUpdate`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StatusUpdate().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The state displayed with the ADB Device when running "adb devices"
  public enum DeviceState: Codable, Equatable, Sendable {
    /// The device state is unknown.
    case unspecified
    /// The ADB device is in the "device" status.
    case device
    /// The ADB device is in the "recovery" status.
    case recovery
    /// The ADB device is in the "rescue" status.
    case rescue
    /// The ADB device is in the "sideload" status.
    case sideload
    /// The ADB device is in the "missing" status.
    case missing
    /// The ADB device is in the "offline" status.
    case offline
    /// The ADB device is in the "unauthorized" status.
    case unauthorized
    /// The ADB device is in the "authorizing" status.
    case authorizing
    /// The ADB device is in the "connecting" status.
    case connecting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .device: return 1
      case .recovery: return 2
      case .rescue: return 3
      case .sideload: return 4
      case .missing: return 10
      case .offline: return 11
      case .unauthorized: return 12
      case .authorizing: return 13
      case .connecting: return 14
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DEVICE_STATE_UNSPECIFIED"
      case .device: return "DEVICE"
      case .recovery: return "RECOVERY"
      case .rescue: return "RESCUE"
      case .sideload: return "SIDELOAD"
      case .missing: return "MISSING"
      case .offline: return "OFFLINE"
      case .unauthorized: return "UNAUTHORIZED"
      case .authorizing: return "AUTHORIZING"
      case .connecting: return "CONNECTING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DeviceState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DEVICE_STATE_UNSPECIFIED": self = .unspecified
      case "DEVICE": self = .device
      case "RECOVERY": self = .recovery
      case "RESCUE": self = .rescue
      case "SIDELOAD": self = .sideload
      case "MISSING": self = .missing
      case "OFFLINE": self = .offline
      case "UNAUTHORIZED": self = .unauthorized
      case "AUTHORIZING": self = .authorizing
      case "CONNECTING": self = .connecting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DeviceState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .device
      case 2: self = .recovery
      case 3: self = .rescue
      case 4: self = .sideload
      case 10: self = .missing
      case 11: self = .offline
      case 12: self = .unauthorized
      case 13: self = .authorizing
      case 14: self = .connecting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .device: return try container.encode(1)
      case .recovery: return try container.encode(2)
      case .rescue: return try container.encode(3)
      case .sideload: return try container.encode(4)
      case .missing: return try container.encode(10)
      case .offline: return try container.encode(11)
      case .unauthorized: return try container.encode(12)
      case .authorizing: return try container.encode(13)
      case .connecting: return try container.encode(14)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.devicestreaming.v1.StatusUpdate"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
