// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Data for a stream.
public struct StreamData: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The unique ID of this stream, assigned by the client.
  public var streamId: Swift.Int32 = Swift.Int32()

  /// The data of the stream, either bytes or "Close", indicating that the stream
  /// is done.
  public var contents: OneOf_Contents? = nil

  /// Initialize a new instance of `StreamData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamData().with { $0.streamId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case streamId = "streamId"
    case data = "data"
    case close = "close"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.streamId = try container.decode(Swift.Int32.self, forKey: .streamId)

    var contents: OneOf_Contents? = nil
    let contentsCheckAndSet = {
      if contents != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'contents'"))
      }
      contents = $0
    }
    if let data = try container.decodeIfPresent(Foundation.Data.self, forKey: .data) {
      try contentsCheckAndSet(.data(data))
    }
    if let close = try container.decodeIfPresent(Close?.self, forKey: .close) {
      try contentsCheckAndSet(.close(close))
    }
    self.contents = contents
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.streamId, forKey: .streamId)

    if let choice = self.contents {
      switch choice {
      case .data(let value):
        try container.encode(value, forKey: .data)
      case .close(let value):
        try container.encode(value, forKey: .close)
      }
    }
  }

  /// The data of the stream, either bytes or "Close", indicating that the stream
  /// is done.
  public enum OneOf_Contents: Codable, Equatable, Sendable {
    /// Data in the stream.
    case data(Foundation.Data)
    /// The stream is closing. EOF.
    indirect case close(Close?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.devicestreaming.v1.StreamData"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
