// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The result of a stream.
public struct StreamStatus: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The unique ID of this stream, assigned by the client.
  public var streamId: Swift.Int32 = Swift.Int32()

  /// The result of the stream. Either "Okay" for success or "Fail" for failure.
  public var status: OneOf_Status? = nil

  /// Initialize a new instance of `StreamStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamStatus().with { $0.streamId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case streamId = "streamId"
    case okay = "okay"
    case fail = "fail"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.streamId = try container.decode(Swift.Int32.self, forKey: .streamId)

    var status: OneOf_Status? = nil
    let statusCheckAndSet = {
      if status != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'status'"))
      }
      status = $0
    }
    if let okay = try container.decodeIfPresent(Okay?.self, forKey: .okay) {
      try statusCheckAndSet(.okay(okay))
    }
    if let fail = try container.decodeIfPresent(Fail?.self, forKey: .fail) {
      try statusCheckAndSet(.fail(fail))
    }
    self.status = status
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.streamId, forKey: .streamId)

    if let choice = self.status {
      switch choice {
      case .okay(let value):
        try container.encode(value, forKey: .okay)
      case .fail(let value):
        try container.encode(value, forKey: .fail)
      }
    }
  }

  /// The result of the stream. Either "Okay" for success or "Fail" for failure.
  public enum OneOf_Status: Codable, Equatable, Sendable {
    /// Okay for success.
    indirect case okay(Okay?)
    /// Fail for failure.
    indirect case fail(Fail?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.devicestreaming.v1.StreamStatus"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
